const array1 = [
  "ips courier",
  "aact freight shipment",
  "seino transportation",
  "emp order",
  "redbubble order",
  "usc order",
  "nfl shop order",
  "kfc order",
  "kylie cosmetics order",
  "latestone online shopping order",
  "kate spade order",
  "jcp order",
  "gap order",
  "go shop order",
  "interflora order",
  "ftd flowers order",
  "frontier communications order",
  "babies r us order",
  "pottery barn order online",
  "jimmy jazz order",
  "justfab order",
  "pacsun order",
  "j crew factory order",
  "fanatics order",
  "dji order",
  "eyebuydirect order",
  "disney store order",
  "costco order",
  "bed bath and beyond order",
  "asurion shipment",
  "tele2 order online",
  "younique order",
  "sportsmans guide order online",
  "teepublic order",
  "trackr order",
  "wet seal order",
  "silver sprint courier",
  "soccer com order",
  "shoebuy order",
  "restoration hardware order",
  "scentsy order",
  "scrubs and beyond order online",
  "otterbox order",
  "myer order",
  "netflorist order",
  "misspap order",
  "mc order",
  "mac cosmetics order online",
  "liberty shoes order online",
  "lycamobile order online",
  "lakeside collection order",
  "lamps plus order",
  "lenscrafters order",
  "multiple carriers global package",
  "empost uae courier",
  "netherlands post postnl",
  "singpost registered mail",
  "indonesia post",
  "philippines post",
  "parcelnet courier",
  "paypal package",
  "magyar posta hungary post",
  "mexico post",
  "ebay international priority mail shipping",
  "ghana post",
  "belpost belarus",
  "q post qatar parcel",
  "other carrier",
  "bulgarian posts",
  "spain post",
  "malta post ems",
  "italy post",
  "czech republic post",
  "taiwan post",
  "pakistan post",
  "new zealand post",
  "osm worldwide shipping",
  "france post la poste",
  "inpost parcel",
  "eub shipping carrier",
  "posten sweden",
  "cpc canada post corporation package",
  "taxipost",
  "pitney bowes parcel",
  "poland post",
  "sweden post postnord",
  "lebanon liban post ems",
  "nigeria nipost",
  "correo argentino",
  "fto e money order online",
  "pos ekspress track and trace online",
  "sailpost italy courier",
  "cyprus post",
  "germany post",
  "austrian post international",
];

// const Array2 = [
//"17 post service courier",
//"2go courier",
//"360 lion courier",
//"4 72 entregando courier",
//"4px courier",
//"4square group courier",
//"7 horse logistics courier",
//"a r express courier",
//"a1 international courier",
//"a3 express courier",
//"aaa cooper transportation courier",
//"abc transport courier",
//"abf freight",
//"abf freight courier",
//"abx express courier",
//"accurate freight carrier",
//"ace courier",
//"acs courier",
//"acx courier",
//"adicional logistics courier",
//"aditya express courier",
//"ads one courier",
//"air king courier",
//"air star xpress courier",
//"air state courier",
//"air21 courier",
//"airbase express courier",
//"airpak courier",
//"airpak express",
//"airspeed international corporation courier",
//"airstate courier",
//"airwings courier",
//"aj express courier",
//"ajay logistics goods courier",
//"ajw courier",
//"ajw express courier",
//"akash ganga courier",
//"akashdoot courier",
//"akr express courier",
//"albanian courier",
//"ample express courier",
//"ams courier",
//"an post courier",
//"anjani courier",
//"apc overnight courier",
//"apc postal",
//"apc postal logistics courier",
//"apex courier",
//"aramex australia",
//"aramex courier",
//"arc carrier",
//"arrow xl courier",
//"asendia germany courier",
//"asendia hk courier",
//"asendia uk courier",
//"asendia usa",
//"asendia usa courier",
//"asm courier",
//"asmi express courier",
//"ats amazon shipping",
//"ats courier",
//"au post china courier",
//"australia express post courier",
//"australia post",
//"australia post courier",
//"austrian post courier",
//"averitt express courier",
//"avinash carier transport acpl courier",
//"b2c europe courier",
//"b4 express courier",
//"belgium post courier",
//"belpost courier",
//"bert transport courier",
//"best express courier",
//"better trucks",
//"bharat motor parcel courier",
//"bhavani courier",
//"big guy courier",
//"blue dart courier",
//"bmp surface courier",
//"bnl courier",
//"bom gim courier",
//"bombay gujarat transport courier",
//"bombino courier",
//"bonds courier",
//"bonds couriers courier",
//"bonds logistics courier",
//"book my packet courier",
//"border express",
//"boxc courier",
//"bpl cargo courier",
//"bpost courier",
//"bpost international courier",
//"brandt truck line courier",
//"brazil correios",
//"brazil correios courier",
//"bright courier",
//"brizo global cargo courier",
//"brt bartolini courier",
//"budget courier",
//"bulgarian posts courier",
//"buylogic courier",
//"c & t courier",
//"cambodia post courier",
//"canada post",
//"canada post courier",
//"canada post courier",
//"canpar courier",
//"canpar courier courier",
//"caper courier",
//"cbl logistics courier",
//"cci courier",
//"central freight lines courier",
//"ceva courier",
//"chetak logistics courier",
//"china ems courier",
//"china post",
//"china post courier",
//"chronopost france courier",
//"chronopost portugal courier",
//"citi network courier",
//"citipost courier",
//"city express courier",
//"city link courier",
//"city link express",
//"city link express courier",
//"city link international courier",
//"city link express courier",
//"cj gls courier",
//"cj packet",
//"classic courier",
//"cma cgm",
//"cma cgm courier",
//"cne express courier",
//"colis privé courier",
//"colissimo courier",
//"colissimo courier",
//"collect courier",
//"collect+ courier",
//"combined courier",
//"con way freight",
//"con way freight courier",
//"concor courier",
//"connectindia courier",
//"continental courier",
//"corporate courier",
//"corporate express",
//"correis courier",
//"correo argentino courier",
//"correos chile courier",
//"correos de españa courier",
//"correos de mexico courier",
//"correos express courier",
//"cosco courier",
//"cosmetics now courier",
//"cosmic courier",
//"country wide courier",
//"courex courier",
//"courier it courier",
//"courier network courier",
//"courier nz courier",
//"courier plus courier",
//"courier post",
//"courierpost courier",
//"couriers please",
//"couriers please courier",
//"couriers please courier",
//"cpacket courier",
//"crown world wide courier",
//"ctt courier",
//"cuckoo express courier",
//"cyprus post courier",
//"dachser courier",
//"dats trucking courier",
//"dawn wing courier",
//"dayton freight lines courier",
//"db schenker sweden courier",
//"deb air courier",
//"deccan queen courier",
//"delcart courier",
//"delex courier",
//"delhivery courier",
//"delivree king courier",
//"delnet express",
//"deltec courier",
//"detrack courier",
//"deutsche post dhl",
//"deutsche post mail courier",
//"deutscsche post courier",
//"dg global forwarding courier",
//"dhl active",
//"dhl courier",
//"dhl ecommerce asia",
//"dhl express",
//"dhl global forwarding",
//"dhl global mail",
//"dhl pieceid",
//"diacom canada",
//"digital courier",
//"dinland courier",
//"direct freight express courier",
//"direct link courier",
//"direct way cargo courier",
//"divine courier",
//"dmm network courier",
//"dnx cargo courier",
//"dohrn transfer company courier",
//"dotzot courier",
//"dpd",
//"dpd courier",
//"dpd courier",
//"dpd uk",
//"dpd us",
//"dpe express courier",
//"dpe south africa courier",
//"dpex worldwide courier",
//"drp courier",
//"drtc",
//"dsv courier",
//"dtdc australia",
//"dtdc courier",
//"dtdc express global",
//"dtdc singapore",
//"dtdc uae",
//"dtdc usa",
//"dtrans courier",
//"durga courier",
//"dx courier",
//"dynamic logistics courier",
//"dynamic parcel courier",
//"eagle courier",
//"eastern air courier",
//"easy courier courier",
//"easy mail courier",
//"ec express courier",
//"ec first class courier",
//"ecargo courier",
//"echo courier",
//"ecom express courier",
//"economy international courier",
//"ekart courier",
//"elbee courier",
//"elbex courier",
//"elta courier",
//"elta hellenic post courier",
//"emirates post courier",
//"emirates post courier",
//"emps express courier",
//"ensenda courier",
//"envialia courier",
//"equick china courier",
//"ers courier",
//"esi courier courier",
//"esquire courier",
//"estafeta courier",
//"estes courier",
//"estes courier",
//"evergreen courier",
//"exapaq courier",
//"excellent courier",
//"expeditors courier",
//"expressit courier",
//"falcon courier",
//"fastrak services courier",
//"fedex",
//"fedex cross border",
//"fedex freight",
//"fedex india courier",
//"fedex uk",
//"fedex us",
//"fercam logistics transport courier",
//"first connection courier",
//"first flight courier",
//"first flight couriers courier",
//"first logistics courier",
//"flash courier courier",
//"flash freight logistics courier",
//"flyking courier",
//"flyt express courier",
//"fsc courier",
//"g somani courier",
//"galaxy express courier",
//"garudavega courier",
//"gati kwe courier",
//"gd express courier",
//"gdex",
//"gdex courier",
//"geniki taxydromiki courier",
//"geodis calberson france courier",
//"giao hàng nhanh courier",
//"globegistics inc courier",
//"glodcross cargo courier",
//"gls",
//"gls courier",
//"gls courier",
//"gls courier",
//"gls czech republic",
//"gls italy courier",
//"gls netherlands courier",
//"gms courier",
//"gms express courier",
//"gms worldwide",
//"gofly courier",
//"gojavas courier",
//"grand slam express",
//"greenways courier",
//"greyhound courier",
//"greyhound courier",
//"hari om courier",
//"hermes courier",
//"hermes germany",
//"hermes germany courier",
//"hermes world",
//"hermesworld courier",
//"hindustan courier",
//"holland freight courier",
//"homedirect logistics courier",
//"hong kong post courier",
//"hong kong post courier",
//"hrvatska pošta courier",
//"hua han logistics courier",
//"humburgg sud courier",
//"ib express courier",
//"ideal courier",
//"i courier",
//"idex courier",
//"imx mail courier",
//"india post",
//"india post domestic courier",
//"india post international",
//"india post international courier",
//"indiaontime courier",
//"indo express courier",
//"inpost paczkomaty courier",
//"interlink express courier",
//"international seur courier",
//"iparcel courier",
//"ix trans courier",
//"j b hunt courier",
//"j somani courier",
//"jaipur golden courier",
//"janco ecommerce",
//"japan post",
//"jetex courier",
//"jk courier",
//"jne international courier",
//"jp express courier",
//"jrs express courier",
//"jt express malaysia",
//"jupiter courier",
//"kerry indev express",
//"kesineni courier",
//"khubani courier",
//"kourtier courier",
//"ktm courier",
//"kwe kintetsu world express courier",
//"la poste",
//"lalji mulji courier",
//"laser ship courier",
//"lasership courier",
//"laxmi courier",
//"lds courier",
//"legend cargo courier",
//"leopard courier",
//"leopards courier",
//"lexship courier",
//"linex courier",
//"links courier",
//"looomis courier",
//"madhur courier",
//"mahabali courier",
//"mail boxes etc courier",
//"mainfreight courier",
//"malaysia post flexipack",
//"marudhar courier",
//"maruti courier",
//"maruti nandan courier",
//"matrix courier",
//"megacity courier",
//"meghraj express courier",
//"metro maruti courier",
//"midland courier",
//"mirakle courier",
//"mol courier",
//"national courier",
//"nepal air courier",
//"nepal air courier and cargo courier",
//"nepal post courier",
//"network express courier",
//"new zealand post",
//"nextsmartship",
//"nine star courier",
//"ninjavan courier",
//"nitco courier",
//"north eastern necc courier",
//"nova poshta international",
//"nuvo ex courier",
//"obc on board courier",
//"ocs courier courier",
//"old dominion",
//"om courier",
//"om logistics courier",
//"on dot courier",
//"ondot courier",
//"oocl courier",
//"overnight courier",
//"overnite courier",
//"overnite express courier",
//"overseas courier",
//"oxford express courier",
//"pafex courier",
//"parcel force courier",
//"parisi grand smooth logistics courier",
//"pashupati cargo courier",
//"pcs express courier",
//"pegasus courier",
//"pickrr courier",
//"pickspeed courier",
//"pigeon courier",
//"pitney bowes",
//"polar express",
//"poonam courier",
//"poslaju",
//"post nl courier",
//"poste italiane",
//"postnord courier",
//"prayaas courier",
//"professional courier",
//"professional kuwait",
//"professional singapore",
//"professional srilanka",
//"professional uae",
//"professional usa",
//"purolator",
//"purolator courier",
//"pushpak courier",
//"quantium courier",
//"rapid",
//"rapidconnect",
//"red express",
//"regent courier",
//"registered post",
//"rivigo courier",
//"rl carriers",
//"road runners courier",
//"royal international courier",
//"rpx courier",
//"safexpress courier",
//"safexpress india",
//"safmarine courier",
//"sagawa courier",
//"saia courier",
//"sameday courier",
//"saudi post",
//"saudi post courier",
//"scudex express courier",
//"sda express courier",
//"sf express courier",
//"shadowfax courier",
//"shipdelight courier",
//"shiprocket courier",
//"shree anjani courier",
//"shree balaji courier",
//"shree mahavir courier",
//"shree maruti courier",
//"shree nandan courier",
//"shree tirupati courier",
//"sigma courier",
//"singapore post courier",
//"skyking courier",
//"skyman courier",
//"skynet australia",
//"skynet courier",
//"skynet germany",
//"skynet india",
//"skynet malaysia",
//"skynet mexico",
//"skynet nigeria",
//"skynet pakistan",
//"skynet philippines",
//"skynet singapore",
//"skynet uae",
//"skynet usa",
//"skynet worldwide express",
//"skynet yemen",
//"smsa express",
//"south african post courier",
//"spee dee",
//"speed & safe courier",
//"speed post",
//"speedex courier",
//"speedypost llp courier",
//"spoton courier",
//"st courier",
//"star track courier",
//"store viva courier",
//"swiss post",
//"target courier",
//"tci express courier",
//"tci freight courier",
//"tci xps courier",
//"tcs courier",
//"tej courier",
//"thailand post courier",
//"tirupati courier",
//"tnt courier",
//"tnt reference",
//"tnt uk",
//"toll group courier",
//"trackon courier",
//"ubx courier",
//"uk mail courier",
//"united courier",
//"united sajha courier",
//"ups courier",
//"usps courier",
//"v express courier",
//"v trans courier",
//"v xpress courier",
//"vichare courier",
//"vision international cargo courier",
//"vrl courier",
//"vrl logistics courier",
//"vtrans courier",
//"vulcan courier",
//"winit courier",
//"wow express courier",
//"xdel courier",
//"xpressbees courier",
//"xps courier",
//"yamato japan",
//"yang ming courier",
//"yodel courier",
//"yrc freight courier",
//"yrc frieght",
//"yun express",
//"zto express",
// ];
