const couriers = [
  {
    name: "Aact freight shipment",
    link: "aact-freight-shipment-tracking",
  },
  { name: "Asurion shipment", link: "asurion-shipment-tracking" },
  {
    name: "Austrian post international",
    link: "austrian-post-international-tracking",
  },
  { name: "Babies r us", link: "babies-r-us-order-tracking" },
  {
    name: "Bed bath and beyond",
    link: "bed-bath-and-beyond-order-tracking",
  },
  { name: "Belpost belarus", link: "belpost-belarus-tracking" },
  { name: "Bulgarian posts", link: "bulgarian-posts-tracking" },
  { name: "Correo argentino", link: "correo-argentino-tracking" },
  { name: "Costco", link: "costco-order-tracking" },
  {
    name: "Cpc canada post corporation package",
    link: "cpc-canada-post-corporation-package-tracking",
  },
  { name: "Cyprus post", link: "cyprus-post-tracking" },
  { name: "Czech republic post", link: "czech-republic-post-tracking" },
  { name: "Disney store", link: "disney-store-order-tracking" },
  { name: "Dji", link: "dji-order-tracking" },
  {
    name: "Ebay international priority mail shipping",
    link: "ebay-international-priority-mail-shipping-tracking",
  },
  { name: "Emp", link: "emp-order-tracking" },
  { name: "Empost uae courier", link: "empost-uae-courier-tracking" },
  {
    name: "Eub shipping carrier",
    link: "eub-shipping-carrier-tracking",
  },
  { name: "Eyebuydirect", link: "eyebuydirect-order-tracking" },
  { name: "Fanatics", link: "fanatics-order-tracking" },
  {
    name: "France post la poste",
    link: "france-post-la-poste-tracking",
  },
  {
    name: "Frontier communications",
    link: "frontier-communications-order-tracking",
  },
  { name: "Ftd flowers", link: "ftd-flowers-order-tracking" },
  { name: "Fto e money online", link: "fto-e-money-tracking" },
  { name: "Gap", link: "gap-order-tracking" },
  { name: "Germany post", link: "germany-post-tracking" },
  { name: "Ghana post", link: "ghana-post-tracking" },
  { name: "Go shop", link: "go-shop-order-tracking" },
  { name: "Indonesia post", link: "indonesia-post-tracking" },
  { name: "Inpost parcel", link: "inpost-parcel-tracking" },
  { name: "Interflora", link: "interflora-order-tracking" },
  { name: "Ips courier", link: "ips-courier-tracking" },
  { name: "Italy post", link: "italy-post-tracking" },
  { name: "J crew factory", link: "j-crew-factory-order-tracking" },
  { name: "Jcp", link: "jcp-order-tracking" },
  { name: "Jimmy jazz", link: "jimmy-jazz-order-tracking" },
  { name: "Justfab", link: "justfab-order-tracking" },
  { name: "Kate spade", link: "kate-spade-order-tracking" },
  { name: "Kfc", link: "kfc-order-tracking" },
  { name: "Kylie cosmetics", link: "kylie-cosmetics-order-tracking" },
  {
    name: "Lakeside collection",
    link: "lakeside-collection-order-tracking",
  },
  { name: "Lamps plus", link: "lamps-plus-order-tracking" },
  {
    name: "Latestone online shopping",
    link: "latestone-online-shopping-order-tracking",
  },
  {
    name: "Lebanon liban post ems",
    link: "lebanon-liban-post-ems-tracking",
  },
  { name: "Lenscrafters", link: "lenscrafters-order-tracking" },
  { name: "Liberty shoes online", link: "liberty-shoes-tracking" },
  { name: "Lycamobile online", link: "lycamobile-tracking" },
  { name: "Mac cosmetics online", link: "mac-cosmetics-tracking" },
  {
    name: "Magyar posta hungary post",
    link: "magyar-posta-hungary-post-tracking",
  },
  { name: "Malta post ems", link: "malta-post-ems-tracking" },
  { name: "Mc", link: "mc-order-tracking" },
  { name: "Mexico post", link: "mexico-post-tracking" },
  { name: "Misspap", link: "misspap-order-tracking" },
  {
    name: "Multiple carriers global package",
    link: "multiple-carriers-global-package-tracking",
  },
  { name: "Myer", link: "myer-order-tracking" },
  { name: "Netflorist", link: "netflorist-order-tracking" },
  {
    name: "Netherlands post postnl",
    link: "netherlands-post-postnl-tracking",
  },
  { name: "New zealand post", link: "new-zealand-post-tracking" },
  { name: "Nfl shop", link: "nfl-shop-order-tracking" },
  { name: "Nigeria nipost", link: "nigeria-nipost-tracking" },
  {
    name: "Osm worldwide shipping",
    link: "osm-worldwide-shipping-tracking",
  },
  { name: "Other carrier", link: "other-carrier-tracking" },
  { name: "Otterbox", link: "otterbox-order-tracking" },
  { name: "Pacsun", link: "pacsun-order-tracking" },
  { name: "Pakistan post", link: "pakistan-post-tracking" },
  { name: "Parcelnet courier", link: "parcelnet-courier-tracking" },
  { name: "Paypal package", link: "paypal-package-tracking" },
  { name: "Philippines post", link: "philippines-post-tracking" },
  {
    name: "Pitney bowes parcel",
    link: "pitney-bowes-parcel-tracking",
  },
  { name: "Poland post", link: "poland-post-tracking" },
  {
    name: "Pos ekspress track and trace online",
    link: "pos-ekspress-track-and-trace-online-tracking",
  },
  { name: "Posten sweden", link: "posten-sweden-tracking" },
  { name: "Pottery barn online", link: "pottery-barn-tracking" },
  {
    name: "Q post qatar parcel",
    link: "q-post-qatar-parcel-tracking",
  },
  { name: "Redbubble", link: "redbubble-order-tracking" },
  {
    name: "Restoration hardware",
    link: "restoration-hardware-order-tracking",
  },
  {
    name: "Sailpost italy courier",
    link: "sailpost-italy-courier-tracking",
  },
  { name: "Scentsy", link: "scentsy-order-tracking" },
  {
    name: "Scrubs and beyond online",
    link: "scrubs-and-beyond-tracking",
  },
  {
    name: "Seino transportation",
    link: "seino-transportation-tracking",
  },
  { name: "Shoebuy", link: "shoebuy-order-tracking" },
  {
    name: "Silver sprint courier",
    link: "silver-sprint-courier-tracking",
  },
  {
    name: "Singpost registered mail",
    link: "singpost-registered-mail-tracking",
  },
  { name: "Soccer com", link: "soccer-com-order-tracking" },
  { name: "Spain post", link: "spain-post-tracking" },
  {
    name: "Sportsmans guide online",
    link: "sportsmans-guide-tracking",
  },
  {
    name: "Sweden post postnord",
    link: "sweden-post-postnord-tracking",
  },
  { name: "Taiwan post", link: "taiwan-post-tracking" },
  { name: "Taxipost", link: "taxipost-tracking" },
  { name: "Teepublic", link: "teepublic-order-tracking" },
  { name: "Tele2 online", link: "tele2-tracking" },
  { name: "Trackr", link: "trackr-order-tracking" },
  { name: "Usc", link: "usc-order-tracking" },
  { name: "Wet seal", link: "wet-seal-order-tracking" },
  { name: "Younique", link: "younique-order-tracking" },
];
